[package]
name = "tile-engine"
version.workspace = true
edition.workspace = true

[dependencies]
pdf-kernel = { path = "../pdf-kernel" }
memory-governor = { path = "../memory-governor" }
image.workspace = true
log.workspace = true
parking_lot.workspace = true
crossbeam-channel.workspace = true
rayon.workspace = true
thiserror.workspace = true
